program FC91;

uses
  FMX.Forms,
  FrmMain in 'App\FrmMain.pas' {FormMain},
  FrmAction in 'App\FrmAction.pas' {FormAction},
  FrmMemo in 'App\FrmMemo.pas' {FormMemo},
  FrmBambu in 'App\FrmBambu.pas' {FormBambu},
  FrmColor in 'App\FrmColor.pas' {FormColor},
  FrmImage in 'App\FrmImage.pas' {FormImage},
  RiggVar.App.Main in 'App\RiggVar.App.Main.pas',
  RiggVar.App.Main0 in 'App\RiggVar.App.Main0.pas',
  RiggVar.Bitmap.Bands in 'Bitmap\RiggVar.Bitmap.Bands.pas',
  RiggVar.Bitmap.Bands01 in 'Bitmap\RiggVar.Bitmap.Bands01.pas',
  RiggVar.Bitmap.Bitmap00 in 'Bitmap\RiggVar.Bitmap.Bitmap00.pas',
  RiggVar.Bitmap.Bitmap02 in 'Bitmap\RiggVar.Bitmap.Bitmap02.pas',
  RiggVar.Bitmap.Bitmap99 in 'Bitmap\RiggVar.Bitmap.Bitmap99.pas',
  RiggVar.Bitmap.Strips in 'Bitmap\RiggVar.Bitmap.Strips.pas',
  RiggVar.Bitmap.Strips01 in 'Bitmap\RiggVar.Bitmap.Strips01.pas',
  RiggVar.Bitmap.Texture in 'Bitmap\RiggVar.Bitmap.Texture.pas',
  RiggVar.EQ.Equation01 in 'EQ\RiggVar.EQ.Equation01.pas',
  RiggVar.EQ.Equation02 in 'EQ\RiggVar.EQ.Equation02.pas',
  RiggVar.EQ.Equation03 in 'EQ\RiggVar.EQ.Equation03.pas',
  RiggVar.EQ.Equation04 in 'EQ\RiggVar.EQ.Equation04.pas',
  RiggVar.EQ.Equation0N in 'EQ\RiggVar.EQ.Equation0N.pas',
  RiggVar.EQ.Equation0S in 'EQ\RiggVar.EQ.Equation0S.pas',
  RiggVar.EQ.Equation01Diff in 'EQ\RiggVar.EQ.Equation01Diff.pas',
  RiggVar.EQ.Equation02Diff in 'EQ\RiggVar.EQ.Equation02Diff.pas',
  RiggVar.EQ.Equation03Diff in 'EQ\RiggVar.EQ.Equation03Diff.pas',
  RiggVar.EQ.Model in 'EQ\RiggVar.EQ.Model.pas',
  RiggVar.EQ.SimpleFormula in 'EQ\RiggVar.EQ.SimpleFormula.pas',
  RiggVar.FB.Action in 'FB\RiggVar.FB.Action.pas',
  RiggVar.FB.ActionConfig in 'FB\RiggVar.FB.ActionConfig.pas',
  RiggVar.FB.ActionConst in 'FB\RiggVar.FB.ActionConst.pas',
  RiggVar.FB.ActionDecode in 'FB\RiggVar.FB.ActionDecode.pas',
  RiggVar.FB.ActionDef in 'FB\RiggVar.FB.ActionDef.pas',
  RiggVar.FB.ActionEncode in 'FB\RiggVar.FB.ActionEncode.pas',
  RiggVar.FB.ActionGroup in 'FB\RiggVar.FB.ActionGroup.pas',
  RiggVar.FB.ActionGroups in 'FB\RiggVar.FB.ActionGroups.pas',
  RiggVar.FB.ActionKeys in 'FB\RiggVar.FB.ActionKeys.pas',
  RiggVar.FB.ActionLong in 'FB\RiggVar.FB.ActionLong.pas',
  RiggVar.FB.ActionMap in 'FB\RiggVar.FB.ActionMap.pas',
  RiggVar.FB.ActionName in 'FB\RiggVar.FB.ActionName.pas',
  RiggVar.FB.ActionShort in 'FB\RiggVar.FB.ActionShort.pas',
  RiggVar.FB.ActionTest in 'FB\RiggVar.FB.ActionTest.pas',
  RiggVar.FB.Bitmap in 'FB\RiggVar.FB.Bitmap.pas',
  RiggVar.FB.Bundle in 'FB\RiggVar.FB.Bundle.pas',
  RiggVar.FB.Classes in 'FB\RiggVar.FB.Classes.pas',
  RiggVar.FB.Color in 'FB\RiggVar.FB.Color.pas',
  RiggVar.FB.ColorBambu in 'FB\RiggVar.FB.ColorBambu.pas',
  RiggVar.FB.ColorConst in 'FB\RiggVar.FB.ColorConst.pas',
  RiggVar.FB.ColorGroup in 'FB\RiggVar.FB.ColorGroup.pas',
  RiggVar.FB.ColorList in 'FB\RiggVar.FB.ColorList.pas',
  RiggVar.FB.ColorListBox in 'FB\RiggVar.FB.ColorListBox.pas',
  RiggVar.FB.ColorListBoxP in 'FB\RiggVar.FB.ColorListBoxP.pas',
  RiggVar.FB.ColorListBoxWeb in 'FB\RiggVar.FB.ColorListBoxWeb.pas',
  RiggVar.FB.Data in 'FB\RiggVar.FB.Data.pas',
  RiggVar.FB.Def in 'FB\RiggVar.FB.Def.pas',
  RiggVar.FB.DefConst in 'FB\RiggVar.FB.DefConst.pas',
  RiggVar.FB.Equation in 'FB\RiggVar.FB.Equation.pas',
  RiggVar.FB.Formula in 'FB\RiggVar.FB.Formula.pas',
  RiggVar.FB.Frame in 'FB\RiggVar.FB.Frame.pas',
  RiggVar.FB.Graph in 'FB\RiggVar.FB.Graph.pas',
  RiggVar.FB.Hub in 'FB\RiggVar.FB.Hub.pas',
  RiggVar.FB.ListArray in 'FB\RiggVar.FB.ListArray.pas',
  RiggVar.FB.Logger in 'FB\RiggVar.FB.Logger.pas',
  RiggVar.FB.MeshParams in 'FB\RiggVar.FB.MeshParams.pas',
  RiggVar.FB.Model in 'FB\RiggVar.FB.Model.pas',
  RiggVar.FB.Params in 'FB\RiggVar.FB.Params.pas',
  RiggVar.FB.ParamDef in 'FB\RiggVar.FB.ParamDef.pas',
  RiggVar.FB.Report in 'FB\RiggVar.FB.Report.pas',
  RiggVar.FB.Scheme in 'FB\RiggVar.FB.Scheme.pas',
  RiggVar.FB.StopWatch in 'FB\RiggVar.FB.StopWatch.pas',
  RiggVar.FB.Text in 'FB\RiggVar.FB.Text.pas',
  RiggVar.FB.TextBase in 'FB\RiggVar.FB.TextBase.pas',
  RiggVar.FB.Transform in 'FB\RiggVar.FB.Transform.pas',
  RiggVar.FB.Update in 'FB\RiggVar.FB.Update.pas',
  RiggVar.Mesh.BuilderMesh in 'Mesh\RiggVar.Mesh.BuilderMesh.pas',
  RiggVar.Mesh.ExporterOBJ in 'Mesh\RiggVar.Mesh.ExporterOBJ.pas',
  RiggVar.Mesh.FederShell1 in 'Mesh\RiggVar.Mesh.FederShell1.pas',
  RiggVar.Mesh.FederMesh in 'Mesh\RiggVar.Mesh.FederMesh.pas',
  RiggVar.Mesh.MeshBuilder in 'Mesh\RiggVar.Mesh.MeshBuilder.pas',
  RiggVar.Mesh.MeshDataHelper in 'Mesh\RiggVar.Mesh.MeshDataHelper.pas',
  RiggVar.Mesh.SolidPart in 'Mesh\RiggVar.Mesh.SolidPart.pas',
  RiggVar.Mesh.Stitcher in 'Mesh\RiggVar.Mesh.Stitcher.pas',
  RiggVar.MeshBuilder.BorderBand in 'MeshBuilder\RiggVar.MeshBuilder.BorderBand.pas',
  RiggVar.MeshBuilder.BorderBuilder in 'MeshBuilder\RiggVar.MeshBuilder.BorderBuilder.pas',
  RiggVar.MeshBuilder.BorderBuilder1 in 'MeshBuilder\RiggVar.MeshBuilder.BorderBuilder1.pas',
  RiggVar.FederModel.Action in 'Model\RiggVar.FederModel.Action.pas',
  RiggVar.FederModel.ActionChecked in 'Model\RiggVar.FederModel.ActionChecked.pas',
  RiggVar.FederModel.ActionExecute in 'Model\RiggVar.FederModel.ActionExecute.pas',
  RiggVar.FederModel.ActionMapPhone in 'Model\RiggVar.FederModel.ActionMapPhone.pas',
  RiggVar.FederModel.ActionMapTablet in 'Model\RiggVar.FederModel.ActionMapTablet.pas',
  RiggVar.FederModel.ActionMapTransit in 'Model\RiggVar.FederModel.ActionMapTransit.pas',
  RiggVar.FederModel.Binding in 'Model\RiggVar.FederModel.Binding.pas',
  RiggVar.FederModel.Color in 'Model\RiggVar.FederModel.Color.pas',
  RiggVar.FederModel.CornerCube in 'Model\RiggVar.FederModel.CornerCube.pas',
  RiggVar.FederModel.CornerPlane in 'Model\RiggVar.FederModel.CornerPlane.pas',
  RiggVar.FederModel.Data in 'Model\RiggVar.FederModel.Data.pas',
  RiggVar.FederModel.Format in 'Model\RiggVar.FederModel.Format.pas',
  RiggVar.FederModel.Frame3D in 'Model\RiggVar.FederModel.Frame3D.pas',
  RiggVar.FederModel.Graph in 'Model\RiggVar.FederModel.Graph.pas',
  RiggVar.FederModel.Keyboard01 in 'Model\RiggVar.FederModel.Keyboard01.pas',
  RiggVar.FederModel.MaterialSources in 'Model\RiggVar.FederModel.MaterialSources.pas',
  RiggVar.FederModel.Memory in 'Model\RiggVar.FederModel.Memory.pas',
  RiggVar.FederModel.Menu in 'Model\RiggVar.FederModel.Menu.pas',
  RiggVar.FederModel.Palette in 'Model\RiggVar.FederModel.Palette.pas',
  RiggVar.FederModel.Report in 'Model\RiggVar.FederModel.Report.pas',
  RiggVar.FederModel.RingBuilder in 'Model\RiggVar.FederModel.RingBuilder.pas',
  RiggVar.FederModel.SampleManager in 'Model\RiggVar.FederModel.SampleManager.pas',
  RiggVar.FederModel.SampleRepo in 'Model\RiggVar.FederModel.SampleRepo.pas',
  RiggVar.FederModel.SDB010H00 in 'SDB010\RiggVar.FederModel.SDB010H00.pas',
  RiggVar.FederModel.SDB050H00 in 'SDB050\RiggVar.FederModel.SDB050H00.pas',
  RiggVar.FederModel.SDB050H01 in 'SDB050\RiggVar.FederModel.SDB050H01.pas',
  RiggVar.FederModel.SDB050H02 in 'SDB050\RiggVar.FederModel.SDB050H02.pas',
  RiggVar.FederModel.SDB050H03 in 'SDB050\RiggVar.FederModel.SDB050H03.pas',
  RiggVar.FederModel.SDB050H04 in 'SDB050\RiggVar.FederModel.SDB050H04.pas',
  RiggVar.FederModel.TextContainer in 'Model\RiggVar.FederModel.TextContainer.pas',
  RiggVar.FederModel.Touch in 'Model\RiggVar.FederModel.Touch.pas',
  RiggVar.FederModel.TouchBase in 'Model\RiggVar.FederModel.TouchBase.pas',
  RiggVar.FederModel.TouchPhone in 'Model\RiggVar.FederModel.TouchPhone.pas',
  RiggVar.Util.ActionSorter in 'Util\RiggVar.Util.ActionSorter.pas',
  RiggVar.Util.ActionTable in 'Util\RiggVar.Util.ActionTable.pas',
  RiggVar.Util.AppUtils in 'Util\RiggVar.Util.AppUtils.pas',
  RiggVar.Util.BitmapCache in 'Util\RiggVar.Util.BitmapCache.pas',
  RiggVar.Util.BitmapImprinter in 'Util\RiggVar.Util.BitmapImprinter.pas',
  RiggVar.Poly.Rack in 'Poly\RiggVar.Poly.Rack.pas',
  RiggVar.Poly.Rad in 'Poly\RiggVar.Poly.Rad.pas';

{$R *.res}

begin
  if Assigned(Application) then
  begin
    Application.Initialize;
    Application.Title := 'FC91K';
    Application.CreateForm(TFormMain, FormMain);
    Application.Run;
  end;

end.
