unit RiggVar.App.InfoFC;

interface

uses
  System.SysUtils,
  System.Classes;

implementation

procedure AddFCInfo(ML: TStrings);
begin
  ML.Add('FC01: FMX, wie FC13, TFederText instead of TFederTouch');
  ML.Add('');
  ML.Add('FC02: VCL 2D, Abgleich mit FC05 am 24.02.14');
  ML.Add('FC03: VCL 2D, wie FC02, nicht in Perforce');
  ML.Add('');
  ML.Add('FC04: VCL InputClient');
  ML.Add('');
  ML.Add('FC05: FMX 2D, wie FC06, abgerüstet, ohne Grid, ohne Animation');
  ML.Add('FC06: FMX 2D, zeichnet direkt auf Canvas, mit Mesh, ohne Touch');
  ML.Add('');
  ML.Add('FC07: VCL mit TeeChart 2D');
  ML.Add('');
  ML.Add('FC08: FMX InputClient, Vergleich mit FC13 (gleichgesetzt 21.02.2014)');
  ML.Add('');
  ML.Add('FC09: VCL InputClient, weniger als FC10, ohne Shapes');
  ML.Add('FC10: VCL InputClient, weniger als FC11');
  ML.Add('FC11: VCL InputClient, weniger als FC12');
  ML.Add('FC12: VCL InputClient');
  ML.Add('');
  ML.Add('FC13: FMX 3D, mit Animation und Effect');
  ML.Add('FC14: wie FR13, mit allen Units');
  ML.Add('FC15: wie FR13, mit GameController');
  ML.Add('FC16: wie FR15, mit DelphiClient, ohne GameController');
  ML.Add('FC17: wie FC15, mit IcsClient, ohne GameController');
  ML.Add('FC18: wie FC15, mit IndyClient, ohne GameController');
  ML.Add('');
  ML.Add('FC19: VCL InputClient');
  ML.Add('FC20: FMX 3D, mit Tabs: V‪iewport, Paintbox, Connection, Couch');
  ML.Add('');
  ML.Add('FC21: FMX 3D, Zwischenstand');
  ML.Add('FC22: FMX 3D, Zwischenstand');
  ML.Add('FC23: FMX 3D, Zwischenstand');
  ML.Add('');
  ML.Add('FC24: FMX InputClient, wie FC08, ohne Menu, ohne Effects');
  ML.Add('FC25: FMX 2D, wie FC05, zeichnet auf Bitmap, mit Touch');
  ML.Add('FC26: VCL Inputclient, wie FC19, Gamepad only');
  ML.Add('FC27: VCL Gamepad Client, ohne Memo''s');
  ML.Add('');
  ML.Add('FC28: FMX 3D, Open Source, nur Hauptformular');
  ML.Add('FC29: FMX 3D, wie FC28, strukturiert, mehrere Units');
  ML.Add('FC30: FMX 3D, wie FC28, nur Hauptformular, mit Droptarget');
  ML.Add('FC31: FMX 3D, wie FC28, strukturiert, Units mit Namespace, mit TouchFrame');
  ML.Add('');
  ML.Add('FC32: FMX 3D, wie FR13, aber Mesh zweimal (ToggleModel)');
  ML.Add('FC33: FMX 3D, leere Oberfläche, nur Ordner Model');
  ML.Add('');
  ML.Add('FC34: FMX, wie FC13, FederInputConnection aktiv');
  ML.Add('FC35: FMX, wie FC13, FederOutputConnection aktiv');
  ML.Add('');
  ML.Add('FC36: FMX 3D, Vorbereitung auf FC38');
  ML.Add('FC37: FMX 2D, Vorbereitung auf FC38, wie FC25, mit Menu und Tile');
  ML.Add('FC38: FMX 2D+3D, FC36 and FC37 kombiniert');
  ML.Add('FC39: FMX 2D, von FC37, ohne Frame3D');
  ML.Add('');
  ML.Add('FC40: VCL, Vergleich mit FC07 und FC13 ');
  ML.Add('FC41: FMX, wie FC38, mit TChart anstelle von Frame2D');
  ML.Add('');
  ML.Add('FC42: FMX, Kopie von FC38, ohne fmx folder ');
  ML.Add('FC43: FMX, Kopie von FC13, ohne fmx folder ');
  ML.Add('');
  ML.Add('FC44: FMX, wie FC13, ohne Effect und Animation');
  ML.Add('FC45: FMX, wie FC38, ohne Effect und Animation');
  ML.Add('');
  ML.Add('FC46: FMX, von FC41, wie FC38, ohne fmx, mit TChart unter 3D');
  ML.Add('FC47: FMX, von FC44, wie FC13, mit Fix-Kamera Shape3D-Scene-Camera');
  ML.Add('');
  ML.Add('FC48: FMX, von FC44, wie FC13, ohne Unit UI, ohne Effect und Animation');
  ML.Add('FC49: FMX, von FC45, wie FC38, ohne Unit UI, ohne Effect und Animation');
  ML.Add('');
  ML.Add('FC50: FMX, von FC13, wie FC13, ohne Unit UI, mit ColorPanel und TrimmTab');
  ML.Add('FC51: FMX, von FC38, wie FC38, ohne Unit UI, mit TrimmTab');
  ML.Add('');
  ML.Add('FC52: FMX 3D, Testprojekt mit FederText only, Graph');
  ML.Add('');
  ML.Add('FC53: FMX 3D, wie FC53M, mit SDB150');
  ML.Add('');
  ML.Add('FC54: FMX 3D, Testproject mit PickRing und TMeshDatahelper in MeshUtils');
  ML.Add('');
  ML.Add('FC55: FMX 3D 54 + 52 + Trackbar');
  ML.Add('');
  ML.Add('FC56: FMX 3D, 54 + RiggVar.FederModel.Frame3D');
  ML.Add('FC57: FMX 3D, 56 + stuff');
  ML.Add('FC58: FMX 3D, 57 + FederText + FederMesh');
  ML.Add('FC59: FMX 3D, 58 + full RiggVar.FederModel.Graph');
  ML.Add('FC60: FMX 3D, 59 + Trackbar + Tiles');
  ML.Add('FC61: FMX 3D, 50 + Memory + full RiggVar.FederModel.Data');
  ML.Add('FC62: FMX 3D, 61 + Equations ');
  ML.Add('FC63: FMX 3D, 62 + DropTarget + fmx folder ');
  ML.Add('');
  ML.Add('FC64: FMX 3D, ');
  ML.Add('FC65: FMX 3D, iPhone 5 Format mit live Memo für Data-Work, Vergleich mit FC53M, ');
  ML.Add('FC66: VCL mit FMX-Container und Memo, Viewport-Format = iPhone 5');
  ML.Add('FC67: VCL mit FMX-Container und Memo und Menu, Viewport-Format = Tablet');
  ML.Add('');
  ML.Add('FC68: FMX 3D, Metropolis UI');
  ML.Add('FC69: Metropolis blank project template');
  ML.Add('');
  ML.Add('FC70: FMX 3D, 1 MainModel, 1 Viewport, 0 Paintbox, FC78 mini');
  ML.Add('FC71: FMX 3D, 1 MainModel, 0 Viewport, 1 Paintbox, Full 2D only');
  ML.Add('FC72: FMX 3D, 2 MainModel, 1 Viewport, 0 Paintbox, Base FC50, Überlagerung');
  ML.Add('FC73: FMX 3D, 2 MainModel, 2 Viewport, 0 Paintbox, Base FC50, mit allen Formen');
  ML.Add('FC74: FMX 3D, 2 MainModel, 2 Viewport, 0 Paintbox, FC73 mini');
  ML.Add('FC75: FMX 3D, 1 MainModel, 1 Viewport, 1 Paintbox, Base FC51');
  ML.Add('FC76: FMX 3D, 2 MainModel, 2 Viewport, 2 Paintbox,');
  ML.Add('FC77: FMX 3D, 3 MainModel, 3 Viewport, 1 Paintbox,');
  ML.Add('FC78: FMX 3D, 1 MainModel, 1 Viewport, 0 Paintbox, Base FC50');
  ML.Add('FC79: FMX 3D, 4 MainModel, 4 Viewport, 0 Paintbox, Base FC73');
  ML.Add('');
  ML.Add('FC80: FMX 3D, Feature-Set = Android version 1.0.0');
  ML.Add('');
  ML.Add('FC81: FMX 3D, 2 Main, 2 x Phone (Selection Game)');
  ML.Add('FC82: FMX 3D, 2 Main, 2 x Tablet');
  ML.Add('FC83: FMX 3D, old project');
  ML.Add('FC84: FMX 3D, minimal portrait phone project');
  ML.Add('FC85: FMX 3D, 1 MainModel, Base FC78, Global vars and ColorPanel removed');
  ML.Add('FC86: FMX 3D, wie FC85, ohne global vars/consts');
  ML.Add('');
  ML.Add('FC87: Folders FB, EQ4, and Color');
  ML.Add('');
  ML.Add('FC88: FMX ImageInserter, Regex test, image path data in dproj');
  ML.Add('FC89: VCL ImageInserter');
  ML.Add('');
  ML.Add('FC90: Compare with FCXE9/FC90 release (new Oktober 2015 FC80)');
  ML.Add('');
  ML.Add('FC91: FC90 + mit fmx folder and Ortho + DropTarget, Forms and more ...');
  ML.Add('FC92: FC90 + mit fmx folder and Ortho');
  ML.Add('FC93: Federgraph 2D Application with MeshLine');
  ML.Add('FC94: Full App with experimental features');
  ML.Add('FC95: wie FC91, mit Output Connection ');
  ML.Add('FC96: wie FC91, mit Input Connection');
  ML.Add('');
  ML.Add('FG01: FMX, wie FC13, mit WebMenu (analog FR01)');
  ML.Add('FG02: FMX, wie FG01, FR and FC kombiniert');
end;

end.
