unit RiggVar.FB.ColorConst;

interface

uses
  System.Classes;

const
  BambulabBasicColors: array [0..29] of TIdentMapEntry = (
    (Value: Integer($FFFFFFFF); Name: 'PLABasic_JadeWhite'),
    (Value: Integer($FFF7E6DE); Name: 'PLABasic_Beige'),
    (Value: Integer($FFE4BD68); Name: 'PLABasic_Gold'),
    (Value: Integer($FFA6A9AA); Name: 'PLABasic_Silver'),
    (Value: Integer($FF8E9089); Name: 'PLABasic_Gray'),
    (Value: Integer($FF847D48); Name: 'PLABasic_Bronze'),
    (Value: Integer($FF9D432C); Name: 'PLABasic_Brown'),
    (Value: Integer($FF6F5034); Name: 'PLABasic_CocoaBrown'),
    (Value: Integer($FF9D2235); Name: 'PLABasic_MaroonRed'),
    (Value: Integer($FFC12E1F); Name: 'PLABasic_Red'),
    (Value: Integer($FFEC008C); Name: 'PLABasic_Magenta'),
    (Value: Integer($FFF55A74); Name: 'PLABasic_Pink'),
    (Value: Integer($FFF5547C); Name: 'PLABasic_HotPink'),
    (Value: Integer($FFFF6A13); Name: 'PLABasic_Orange'),
    (Value: Integer($FFFF9016); Name: 'PLABasic_Pumpkin'),
    (Value: Integer($FFFEC600); Name: 'PLABasic_SunflowerYellow'),
    (Value: Integer($FFF4EE2A); Name: 'PLABasic_Yellow'),
    (Value: Integer($FFBECF00); Name: 'PLABasic_BrightGreen'),
    (Value: Integer($FF00AE42); Name: 'PLABasic_BambuGreen'),
    (Value: Integer($FF3F8E43); Name: 'PLABasic_MistletoeGreen'),
    (Value: Integer($FF00B1B7); Name: 'PLABasic_Turquoise'),
    (Value: Integer($FF0086D6); Name: 'PLABasic_Cyan'),
    (Value: Integer($FF0A2989); Name: 'PLABasic_Blue'),
    (Value: Integer($FFB056B8); Name: 'PLABasic_CobaltBlue'),
    (Value: Integer($FF5E43B7); Name: 'PLABasic_Purple'),
    (Value: Integer($FF482960); Name: 'PLABasic_IndigoPurple'),
    (Value: Integer($FF5B6579); Name: 'PLABasic_BlueGray'),
    (Value: Integer($FFD1D3D5); Name: 'PLABasic_LightGray'),
    (Value: Integer($FF545454); Name: 'PLABasic_DarkGray'),
    (Value: Integer($FF000000); Name: 'PLABasic_Black')
  );

  BambulabMatteColors: array [0..16] of TIdentMapEntry = (
    (Value: Integer($FFFFFFFF); Name: 'PLAMatte_IvoryWhite'),
    (Value: Integer($FFD3B7A7); Name: 'PLAMatte_LatteBrown'),
    (Value: Integer($FFE8DBB7); Name: 'PLAMatte_DesertTan'),
    (Value: Integer($FF9B9EA0); Name: 'PLAMatte_AshGray'),
    (Value: Integer($FFAE96D4); Name: 'PLAMatte_LilacPurple'),
    (Value: Integer($FFE8AFCF); Name: 'PLAMatte_SakuraPink'),
    (Value: Integer($FFF99963); Name: 'PLAMatte_MandarinOrange'),
    (Value: Integer($FFF7D959); Name: 'PLAMatte_LemonYellow'),
    (Value: Integer($FFDE4343); Name: 'PLAMatte_ScarletRed'),
    (Value: Integer($FFBB3D43); Name: 'PLAMatte_DarkRed'),
    (Value: Integer($FF7D6556); Name: 'PLAMatte_DarkBrown'),
    (Value: Integer($FF68724D); Name: 'PLAMatte_DarkGreen'),
    (Value: Integer($FF61C680); Name: 'PLAMatte_GrassGreen'),
    (Value: Integer($FFA3D8E1); Name: 'PLAMatte_IceBlue'),
    (Value: Integer($FF0078BF); Name: 'PLAMatte_MarineBlue'),
    (Value: Integer($FF042F56); Name: 'PLAMatte_DarkBlue'),
    (Value: Integer($FF000000); Name: 'PLAMatte_Charcoal')
    );

  { Copy of AlphaColors in System.UIConsts ( in implementation section) }
  MyAlphaColors: array [0..147] of TIdentMapEntry = (
    (Value: Integer($FFF0F8FF); Name: 'claAliceblue'),
    (Value: Integer($FFFAEBD7); Name: 'claAntiquewhite'),
    (Value: Integer($FF00FFFF); Name: 'claAqua'),
    (Value: Integer($FF7FFFD4); Name: 'claAquamarine'),
    (Value: Integer($FFF0FFFF); Name: 'claAzure'),
    (Value: Integer($FFF5F5DC); Name: 'claBeige'),
    (Value: Integer($FFFFE4C4); Name: 'claBisque'),
    (Value: Integer($FF000000); Name: 'claBlack';),
    (Value: Integer($FFFFEBCD); Name: 'claBlanchedalmond'),
    (Value: Integer($FF0000FF); Name: 'claBlue'),
    (Value: Integer($FF8A2BE2); Name: 'claBlueviolet'),
    (Value: Integer($FFA52A2A); Name: 'claBrown'),
    (Value: Integer($FFDEB887); Name: 'claBurlywood'),
    (Value: Integer($FF5F9EA0); Name: 'claCadetblue'),
    (Value: Integer($FF7FFF00); Name: 'claChartreuse'),
    (Value: Integer($FFD2691E); Name: 'claChocolate'),
    (Value: Integer($FFFF7F50); Name: 'claCoral'),
    (Value: Integer($FF6495ED); Name: 'claCornflowerblue'),
    (Value: Integer($FFFFF8DC); Name: 'claCornsilk'),
    (Value: Integer($FFDC143C); Name: 'claCrimson'),
    (Value: Integer($FF00FFFF); Name: 'claCyan'),
    (Value: Integer($FF00008B); Name: 'claDarkblue'),
    (Value: Integer($FF008B8B); Name: 'claDarkcyan'),
    (Value: Integer($FFB8860B); Name: 'claDarkgoldenrod'),
    (Value: Integer($FFA9A9A9); Name: 'claDarkgray'),
    (Value: Integer($FF006400); Name: 'claDarkgreen'),
    (Value: Integer($FFA9A9A9); Name: 'claDarkgrey'),
    (Value: Integer($FFBDB76B); Name: 'claDarkkhaki'),
    (Value: Integer($FF8B008B); Name: 'claDarkmagenta'),
    (Value: Integer($FF556B2F); Name: 'claDarkolivegreen'),
    (Value: Integer($FFFF8C00); Name: 'claDarkorange'),
    (Value: Integer($FF9932CC); Name: 'claDarkorchid'),
    (Value: Integer($FF8B0000); Name: 'claDarkred'),
    (Value: Integer($FFE9967A); Name: 'claDarksalmon'),
    (Value: Integer($FF8FBC8F); Name: 'claDarkseagreen'),
    (Value: Integer($FF483D8B); Name: 'claDarkslateblue'),
    (Value: Integer($FF2F4F4F); Name: 'claDarkslategray'),
    (Value: Integer($FF2F4F4F); Name: 'claDarkslategrey'),
    (Value: Integer($FF00CED1); Name: 'claDarkturquoise'),
    (Value: Integer($FF9400D3); Name: 'claDarkviolet'),
    (Value: Integer($FFFF1493); Name: 'claDeeppink'),
    (Value: Integer($FF00BFFF); Name: 'claDeepskyblue'),
    (Value: Integer($FF696969); Name: 'claDimgray'),
    (Value: Integer($FF696969); Name: 'claDimgrey'),
    (Value: Integer($FF1E90FF); Name: 'claDodgerblue'),
    (Value: Integer($FFB22222); Name: 'claFirebrick'),
    (Value: Integer($FFFFFAF0); Name: 'claFloralwhite'),
    (Value: Integer($FF228B22); Name: 'claForestgreen'),
    (Value: Integer($FFFF00FF); Name: 'claFuchsia'),
    (Value: Integer($FFDCDCDC); Name: 'claGainsboro'),
    (Value: Integer($FFF8F8FF); Name: 'claGhostwhite'),
    (Value: Integer($FFFFD700); Name: 'claGold'),
    (Value: Integer($FFDAA520); Name: 'claGoldenrod'),
    (Value: Integer($FF808080); Name: 'claGray'),
    (Value: Integer($FF008000); Name: 'claGreen'),
    (Value: Integer($FFADFF2F); Name: 'claGreenyellow'),
    (Value: Integer($FF808080); Name: 'claGrey'),
    (Value: Integer($FFF0FFF0); Name: 'claHoneydew'),
    (Value: Integer($FFFF69B4); Name: 'claHotpink'),
    (Value: Integer($FFCD5C5C); Name: 'claIndianred'),
    (Value: Integer($FF4B0082); Name: 'claIndigo'),
    (Value: Integer($FFFFFFF0); Name: 'claIvory'),
    (Value: Integer($FFF0E68C); Name: 'claKhaki'),
    (Value: Integer($FFE6E6FA); Name: 'claLavender'),
    (Value: Integer($FFFFF0F5); Name: 'claLavenderblush'),
    (Value: Integer($FF7CFC00); Name: 'claLawngreen'),
    (Value: Integer($FFFFFACD); Name: 'claLemonchiffon'),
    (Value: Integer($FFADD8E6); Name: 'claLightblue'),
    (Value: Integer($FFF08080); Name: 'claLightcoral'),
    (Value: Integer($FFE0FFFF); Name: 'claLightcyan'),
    (Value: Integer($FFFAFAD2); Name: 'claLightgoldenrodyellow'),
    (Value: Integer($FFD3D3D3); Name: 'claLightgray'),
    (Value: Integer($FF90EE90); Name: 'claLightgreen'),
    (Value: Integer($FFD3D3D3); Name: 'claLightgrey'),
    (Value: Integer($FFFFB6C1); Name: 'claLightpink'),
    (Value: Integer($FFFFA07A); Name: 'claLightsalmon'),
    (Value: Integer($FF20B2AA); Name: 'claLightseagreen'),
    (Value: Integer($FF87CEFA); Name: 'claLightskyblue'),
    (Value: Integer($FF778899); Name: 'claLightslategray'),
    (Value: Integer($FF778899); Name: 'claLightslategrey'),
    (Value: Integer($FFB0C4DE); Name: 'claLightsteelblue'),
    (Value: Integer($FFFFFFE0); Name: 'claLightyellow'),
    (Value: Integer($FF00FF00); Name: 'claLime'),
    (Value: Integer($FF32CD32); Name: 'claLimegreen'),
    (Value: Integer($FFFAF0E6); Name: 'claLinen'),
    (Value: Integer($FFFF00FF); Name: 'claMagenta'),
    (Value: Integer($FF800000); Name: 'claMaroon'),
    (Value: Integer($FF66CDAA); Name: 'claMediumaquamarine'),
    (Value: Integer($FF0000CD); Name: 'claMediumblue'),
    (Value: Integer($FFBA55D3); Name: 'claMediumorchid'),
    (Value: Integer($FF9370DB); Name: 'claMediumpurple'),
    (Value: Integer($FF3CB371); Name: 'claMediumseagreen'),
    (Value: Integer($FF7B68EE); Name: 'claMediumslateblue'),
    (Value: Integer($FF00FA9A); Name: 'claMediumspringgreen'),
    (Value: Integer($FF48D1CC); Name: 'claMediumturquoise'),
    (Value: Integer($FFC71585); Name: 'claMediumvioletred'),
    (Value: Integer($FF191970); Name: 'claMidnightblue'),
    (Value: Integer($FFF5FFFA); Name: 'claMintcream'),
    (Value: Integer($FFFFE4E1); Name: 'claMistyrose'),
    (Value: Integer($FFFFE4B5); Name: 'claMoccasin'),
    (Value: Integer($FFFFDEAD); Name: 'claNavajowhite'),
    (Value: Integer($FF000080); Name: 'claNavy'),
    (Value: Integer($FFFDF5E6); Name: 'claOldlace'),
    (Value: Integer($FF808000); Name: 'claOlive'),
    (Value: Integer($FF6B8E23); Name: 'claOlivedrab'),
    (Value: Integer($FFFFA500); Name: 'claOrange'),
    (Value: Integer($FFFF4500); Name: 'claOrangered'),
    (Value: Integer($FFDA70D6); Name: 'claOrchid'),
    (Value: Integer($FFEEE8AA); Name: 'claPalegoldenrod'),
    (Value: Integer($FF98FB98); Name: 'claPalegreen'),
    (Value: Integer($FFAFEEEE); Name: 'claPaleturquoise'),
    (Value: Integer($FFDB7093); Name: 'claPalevioletred'),
    (Value: Integer($FFFFEFD5); Name: 'claPapayawhip'),
    (Value: Integer($FFFFDAB9); Name: 'claPeachpuff'),
    (Value: Integer($FFCD853F); Name: 'claPeru'),
    (Value: Integer($FFFFC0CB); Name: 'claPink'),
    (Value: Integer($FFDDA0DD); Name: 'claPlum'),
    (Value: Integer($FFB0E0E6); Name: 'claPowderblue'),
    (Value: Integer($FF800080); Name: 'claPurple'),
    (Value: Integer($FFFF0000); Name: 'claRed'),
    (Value: Integer($FFBC8F8F); Name: 'claRosybrown'),
    (Value: Integer($FF4169E1); Name: 'claRoyalblue'),
    (Value: Integer($FF8B4513); Name: 'claSaddlebrown'),
    (Value: Integer($FFFA8072); Name: 'claSalmon'),
    (Value: Integer($FFF4A460); Name: 'claSandybrown'),
    (Value: Integer($FF2E8B57); Name: 'claSeagreen'),
    (Value: Integer($FFFFF5EE); Name: 'claSeashell'),
    (Value: Integer($FFA0522D); Name: 'claSienna'),
    (Value: Integer($FFC0C0C0); Name: 'claSilver'),
    (Value: Integer($FF87CEEB); Name: 'claSkyblue'),
    (Value: Integer($FF6A5ACD); Name: 'claSlateblue'),
    (Value: Integer($FF708090); Name: 'claSlategray'),
    (Value: Integer($FF708090); Name: 'claSlategrey'),
    (Value: Integer($FFFFFAFA); Name: 'claSnow'),
    (Value: Integer($FF00FF7F); Name: 'claSpringgreen'),
    (Value: Integer($FF4682B4); Name: 'claSteelblue'),
    (Value: Integer($FFD2B48C); Name: 'claTan'),
    (Value: Integer($FF008080); Name: 'claTeal'),
    (Value: Integer($FFD8BFD8); Name: 'claThistle'),
    (Value: Integer($FFFF6347); Name: 'claTomato'),
    (Value: Integer($FF40E0D0); Name: 'claTurquoise'),
    (Value: Integer($FFEE82EE); Name: 'claViolet'),
    (Value: Integer($FFF5DEB3); Name: 'claWheat'),
    (Value: Integer($FFFFFFFF); Name: 'claWhite'),
    (Value: Integer($FFF5F5F5); Name: 'claWhitesmoke'),
    (Value: Integer($FFFFFF00); Name: 'claYellow'),
    (Value: Integer($FF9ACD32); Name: 'claYellowgreen'),
    (Value: Integer($0); Name: 'claNull')
  );

implementation

end.
