unit RiggVar.Mesh.ReaderOBJ;

(*
-
-     F
-    * * *
-   *   *   G
-  *     * *   *
- E - - - H - - - I
-  *     * *         *
-   *   *   *           *
-    * *     *             *
-     D-------A---------------B
-              *
-              (C) federgraph.de
-
*)

interface

uses
  System.Classes,
  System.Math,
  System.Math.Vectors,
  System.Types,
  System.Generics.Collections,
  System.RTLConsts,
  System.SysUtils,
  FMX.Types,
  FMX.Types3D;

type
  TMeshReaderOBJ = class
  private
    FLog: TStrings;
    FLogOwned: Boolean;
    procedure UpdateVB(VB: TVertexBuffer);
    procedure UpdateIB(IB: TIndexBuffer);
    procedure UpdateTE(VB: TVertexBuffer);
    procedure InitTE;
    procedure SetLogList(const Value: TStrings);
  protected
    FV: TList<TPoint3D>;
    T1: TList<Integer>;
    T2: TList<Integer>;
    T3: TList<Integer>;
  public
    SL: TStringList;

    ExportOffsetZ: single;
    pc1: TPointF;
    pc2: TPointF;
    te1: single;
    te2: single;

    CountV: Integer;
    CountF: Integer;

    ErrorV: Integer;
    ErrorF: Integer;

    FileName: string;

    constructor Create;
    destructor Destroy; override;

    procedure LoadTestData(ML: TStrings);
    procedure LoadFromFile(fn: string);

    procedure Parse;
    procedure ParseV(const s: string);
    procedure ParseF(const s: string);

    procedure Update3DBuffers(VB: TVertexBuffer; IB: TIndexBuffer); virtual;

    property LogList: TStrings read FLog write SetLogList;
  end;

implementation

{ TMeshReaderOBJ }

constructor TMeshReaderOBJ.Create;
begin
  FLog := TStringList.Create;
  FLogOwned := True;
  SL := TStringList.Create;

  FV := TList<TPoint3D>.Create;
  T1 := TList<Integer>.Create;
  T2 := TList<Integer>.Create;
  T3 := TList<Integer>.Create;
end;

destructor TMeshReaderOBJ.Destroy;
begin
  if FLogOwned then
    FLog.Free;

  SL.Free;
  FV.Free;
  T1.Free;
  T2.Free;
  T3.Free;

  inherited;
end;

procedure TMeshReaderOBJ.LoadFromFile(fn: string);
begin
  FileName := fn;
  FLog.Clear;

  if FileExists(FileName) then
  begin
    SL.LoadFromFile(fn);
  end
  else
  begin
    FLog.Add(Format('File ''%s''does not exist', [fn]));
    Exit;
  end;

  Parse;
end;

procedure TMeshReaderOBJ.LoadTestData(ML: TStrings);
begin
  ML.Clear;
  ML.Add('mtllib federgraph-material.mtl');
  ML.Add('');
  ML.Add('o federgraph');
  ML.Add('');
  ML.Add('# copyright federgraph.de 2026');
  ML.Add('# generated by FC91');
  ML.Add('');
  ML.Add('# CapValue = 60');
  ML.Add('# MeshSize = 32');
  ML.Add('');
  ML.Add('# Positions.Count = 947');
  ML.Add('# TriangleCount = 1892');
  ML.Add('# DegeneratedTriangleCount = 2');
  ML.Add('');
  ML.Add('v -7.50 -150.00 44.40');
  ML.Add('v -13.74 -142.50 60.00');
  ML.Add('v -7.50 -142.50 31.48');
  ML.Add('# Positions.Count = 947');
  ML.Add('');
  ML.Add('');
  ML.Add('# ');
  ML.Add('usemtl White');
  ML.Add('f 1 2 3');
  ML.Add('f 2 1 4');
  ML.Add('f 5 3 6');
  ML.Add('# TriangleCount = 1892');
  ML.Add('');
end;

procedure TMeshReaderOBJ.Parse;
var
  i: Integer;
  s: string;
begin
  ErrorV := 0;
  ErrorF := 0;

  CountV := 0;
  CountF := 0;

  FV.Clear;

  T1.Clear;
  T2.Clear;
  T3.Clear;


  for i := 0 to SL.Count - 1 do
  begin
    s := SL[i];

    if s.StartsWith('v ') then
    begin
      ParseV(s);
    end
    else if s.StartsWith('f ') then
    begin
      ParseF(s);
    end;
  end;

  FLog.Add('Summary:');
  FLog.Add('');

  FLog.Add(Format('CountV = %d', [CountV]));
  FLog.Add(Format('CountF = %d', [CountF]));
  FLog.Add('');

  if (ErrorV > 0) or (ErrorF > 0) then
  begin
    FLog.Add(Format('ErrorV = %d', [ErrorV]));
    FLog.Add(Format('ErrorF = %d', [ErrorF]));
    FLog.Add('');
  end;

  FLog.Add(Format('FV.Count = %d', [FV.Count]));
  FLog.Add(Format('T1.Count = %d', [T1.Count]));
  FLog.Add(Format('T2.Count = %d', [T2.Count]));
  FLog.Add(Format('T3.Count = %d', [T3.Count]));
  FLog.Add('');

end;

procedure TMeshReaderOBJ.ParseV(const s: string);
var
  t: string;
  a: TArray<string>;
  l: Integer;
  sx, sy, sz: string;
  x, y, z: single;
  OldErrorCount: Integer;
begin
  Inc(CountF);

  t := s.Substring(2);

  a := t.Split([' '], 3);
  l := Length(a);
  if l = 3 then
  begin
    sx := a[0];
    sy := a[1];
    sz := a[2];

    OldErrorCount := ErrorV;
    if not TryStrToFloat(sx, x) then
      Inc(ErrorV);
    if not TryStrToFloat(sy, y) then
      Inc(ErrorV);
    if not TryStrToFloat(sz, z) then
      Inc(ErrorV);

    if ErrorV = OldErrorCount then
    begin
      FV.Add(TPoint3D.Create(x, y, z));
    end;
  end
  else
  begin
    FLog.Add(Format('e = %s', [s]));
  end;
end;

procedure TMeshReaderOBJ.SetLogList(const Value: TStrings);
begin
  if FLogOwned then
    FLog.Free;
  FLogOwned := False;
  FLog := Value;
end;

procedure TMeshReaderOBJ.ParseF(const s: string);
var
  t: string;
  a: TArray<string>;
  l: Integer;
  s1, s2, s3: string;
  f1, f2, f3: Integer;
begin
  Inc(CountV);

  t := s.Substring(2);

  a := t.Split([' '], 3);
  l := Length(a);
  if l = 3 then
  begin
    s1 := a[0].Trim;
    s2 := a[1].Trim;
    s3 := a[2].Trim;

    f1 := StrToIntDef(s1, 0);
    f2 := StrToIntDef(s2, 0);
    f3 := StrToIntDef(s3, 0);

    T1.Add(f1);
    T2.Add(f2);
    T3.Add(f3);
  end
  else
  begin
    FLog.Add(Format('e = %s', [s]));
    Inc(ErrorF)
  end;
end;

procedure TMeshReaderOBJ.Update3DBuffers(VB: TVertexBuffer; IB: TIndexBuffer);
begin
  UpdateVB(VB);
  UpdateTE(VB);
  UpdateIB(IB);
end;

procedure TMeshReaderOBJ.UpdateIB(IB: TIndexBuffer);
var
  i, j: Integer;
begin
  IB.Length := T1.Count * 3;
  for i := 0 to T1.Count - 1 do
  begin
    j := i * 3;
    IB[j] := T1[i]-1;
    IB[j+1] := T3[i]-1;
    IB[j+2] := T2[i]-1;
  end;
end;

procedure TMeshReaderOBJ.UpdateVB(VB: TVertexBuffer);
var
  i: Integer;
begin
  VB.Length := FV.Count;

  for i := 0 to FV.Count - 1 do
  begin
    VB.Vertices[i] := FV[i];
  end;
end;

procedure TMeshReaderOBJ.InitTE;
begin
  te1 := 180;
  te2 := 360;
end;

procedure TMeshReaderOBJ.UpdateTE(VB: TVertexBuffer);
var
  i: Integer;
  u, v: single;
begin
  InitTE;

  for i := 0 to FV.Count - 1 do
  begin
    u := (FV[i].X + te1) / te2;
    v := (FV[i].Z + te1) / te2;
    VB.TexCoord0[i] := PointF(u, v);
  end;
end;

end.
